=== anote2011/excilys-bank/excilys-bank-data/src/main/resources/data/excilys-bank-dbunit.dtd
<!ELEMENT dataset ANY>

<!ELEMENT REF_ROLE EMPTY>
<!ELEMENT REF_ACCOUNT_CATEGORY EMPTY>
<!ELEMENT REF_ACCOUNT_TYPE EMPTY>
<!ELEMENT REF_CARD_TYPE EMPTY>
<!ELEMENT REF_OPERATION_TYPE EMPTY>
<!ELEMENT REF_OPERATION_STATUS EMPTY>
<!ELEMENT USR EMPTY>
<!ELEMENT USR_ROLE EMPTY>
<!ELEMENT ACCOUNT EMPTY>
<!ELEMENT USR_ACCOUNT EMPTY>
<!ELEMENT CARD EMPTY>
<!ELEMENT OPERATION EMPTY>

<!ATTLIST REF_ROLE ID CDATA #REQUIRED>
<!ATTLIST REF_ROLE NAME  CDATA #REQUIRED>
<!ATTLIST REF_ACCOUNT_CATEGORY ID CDATA #REQUIRED>
<!ATTLIST REF_ACCOUNT_CATEGORY NAME CDATA #REQUIRED>
<!ATTLIST REF_ACCOUNT_TYPE ID CDATA #REQUIRED>
<!ATTLIST REF_ACCOUNT_TYPE CATEGORY CDATA #REQUIRED>
<!ATTLIST REF_ACCOUNT_TYPE NAME CDATA #REQUIRED>
<!ATTLIST REF_CARD_TYPE ID CDATA #REQUIRED>
<!ATTLIST REF_CARD_TYPE NAME CDATA #REQUIRED>
<!ATTLIST REF_OPERATION_TYPE ID CDATA #REQUIRED>
<!ATTLIST REF_OPERATION_TYPE NAME CDATA #REQUIRED>
<!ATTLIST REF_OPERATION_STATUS ID CDATA #REQUIRED>
<!ATTLIST REF_OPERATION_STATUS NAME CDATA #REQUIRED>

<!ATTLIST USR ID CDATA #REQUIRED>
<!ATTLIST USR FIRSTNAME CDATA #REQUIRED>
<!ATTLIST USR LASTNAME CDATA #REQUIRED>
<!ATTLIST USR LOGIN CDATA #REQUIRED>
<!ATTLIST USR PASSWORD CDATA #REQUIRED>
<!ATTLIST USR EMAIL CDATA #REQUIRED>

<!ATTLIST USR_ROLE USR_ID CDATA #REQUIRED>
<!ATTLIST USR_ROLE ROLE_ID CDATA #REQUIRED>

<!ATTLIST ACCOUNT ID CDATA #REQUIRED>
<!ATTLIST ACCOUNT NUMBER CDATA #REQUIRED>
<!ATTLIST ACCOUNT TYPE CDATA #REQUIRED>
<!ATTLIST ACCOUNT BALANCE CDATA #REQUIRED>
<!ATTLIST ACCOUNT BALANCE_DATE CDATA #REQUIRED>

<!ATTLIST USR_ACCOUNT USR_ID CDATA #REQUIRED>
<!ATTLIST USR_ACCOUNT ACCOUNT_ID CDATA #REQUIRED>

<!ATTLIST CARD ID CDATA #REQUIRED>
<!ATTLIST CARD NUMBER CDATA #REQUIRED>
<!ATTLIST CARD ACCOUNT CDATA #REQUIRED>
<!ATTLIST CARD TYPE CDATA #REQUIRED>
<!ATTLIST CARD PENDING CDATA "">
<!ATTLIST CARD PENDING_DATE CDATA "">

<!ATTLIST OPERATION ID CDATA #REQUIRED>
<!ATTLIST OPERATION ACCOUNT CDATA #REQUIRED>
<!ATTLIST OPERATION AMOUNT CDATA #REQUIRED>
<!ATTLIST OPERATION DATE CDATA #REQUIRED>
<!ATTLIST OPERATION NAME CDATA #REQUIRED>
<!ATTLIST OPERATION TYPE CDATA #REQUIRED>
<!ATTLIST OPERATION STATUS CDATA #REQUIRED>
<!ATTLIST OPERATION CARD CDATA "">

=== anote2011/excilys-bank/excilys-bank-data/src/main/resources/data/dataSet-02-data-manual.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "excilys-bank-dbunit.dtd">
<dataset>

	<USR ID="1000000000" FIRSTNAME="Stephane" LASTNAME="Landelle" LOGIN="slandelle" PASSWORD="password" EMAIL="slandelle@excilys.com" />
	<USR ID="1000000001" FIRSTNAME="Romain" LASTNAME="Sertelon" LOGIN="rsertelon" PASSWORD="password" EMAIL="rsertelon@excilys.com" />

	<USR_ROLE USR_ID="1000000000" ROLE_ID="ROLE_USER" />
	<USR_ROLE USR_ID="1000000000" ROLE_ID="ROLE_ADMIN" />
	<USR_ROLE USR_ID="1000000001" ROLE_ID="ROLE_USER" />

	<ACCOUNT ID="1000000000" NUMBER="0123456789AAXX" TYPE="PERSONNAL_CHECKING" BALANCE="50.00" BALANCE_DATE="2011-08-02 11:55:01" />
	<ACCOUNT ID="1000000001" NUMBER="0123456789AAYY" TYPE="JOINT_CHECKING" BALANCE="500.00" BALANCE_DATE="2011-08-02 11:55:01" />
	<ACCOUNT ID="1000000002" NUMBER="0123456789AAZZ" TYPE="PEL" BALANCE="1000.00" BALANCE_DATE="2011-08-02 11:55:01" />

	<USR_ACCOUNT USR_ID="1000000000" ACCOUNT_ID="1000000000" />
	<USR_ACCOUNT USR_ID="1000000000" ACCOUNT_ID="1000000001" />
	<USR_ACCOUNT USR_ID="1000000000" ACCOUNT_ID="1000000002" />

	<CARD ID="100000000000" NUMBER="XXXXX1" TYPE="CREDIT" ACCOUNT="1000000000" PENDING="-200" PENDING_DATE="2011-08-02 11:55:01" />
	<CARD ID="100000000001" NUMBER="XXXXX2" TYPE="DEBIT" ACCOUNT="1000000000" />
	<CARD ID="100000000002" NUMBER="XXXXX3" TYPE="DEBIT" ACCOUNT="1000000001" />

	<OPERATION ID="1000000000028" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="CARD" CARD="100000000000" AMOUNT="-100" NAME="cash -100" DATE="2011-07-01 11:55:01" />
	<OPERATION ID="1000000000029" ACCOUNT="1000000000" STATUS="PENDING" TYPE="CARD" CARD="100000000000" AMOUNT="-200" NAME="cash -200" DATE="2011-08-01 11:55:01" />

	<OPERATION ID="1000000000000" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="100" NAME="cash +100" DATE="2011-07-28 11:55:01" />
	<OPERATION ID="1000000000001" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="-200" NAME="cash -200" DATE="2011-07-27 11:55:01" />
	<OPERATION ID="1000000000002" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="300" NAME="cash +300" DATE="2011-07-26 11:55:01" />
	<OPERATION ID="1000000000003" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="100" NAME="cash +100" DATE="2011-07-25 11:55:01" />
	<OPERATION ID="1000000000004" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="-200" NAME="cash -200" DATE="2011-07-24 11:55:01" />
	<OPERATION ID="1000000000005" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="300" NAME="cash +300" DATE="2011-07-23 11:55:01" />
	<OPERATION ID="1000000000006" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="100" NAME="cash +100" DATE="2011-07-22 11:55:01" />
	<OPERATION ID="1000000000007" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="-200" NAME="cash -200" DATE="2011-07-21 11:55:01" />
	<OPERATION ID="1000000000008" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="300" NAME="cash +300" DATE="2011-07-20 11:55:01" />
	<OPERATION ID="1000000000009" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="100" NAME="cash +100" DATE="2011-07-19 11:55:01" />
	<OPERATION ID="1000000000010" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="-200" NAME="cash -200" DATE="2011-07-18 11:55:01" />
	<OPERATION ID="1000000000011" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="300" NAME="cash +300" DATE="2011-07-17 11:55:01" />
	<OPERATION ID="1000000000012" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="100" NAME="cash +100" DATE="2011-07-16 11:55:01" />
	<OPERATION ID="1000000000013" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="-200" NAME="cash -200" DATE="2011-07-15 11:55:01" />
	<OPERATION ID="1000000000014" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="300" NAME="cash +300" DATE="2011-07-14 11:55:01" />
	<OPERATION ID="1000000000015" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="100" NAME="cash +100" DATE="2011-07-13 11:55:01" />
	<OPERATION ID="1000000000016" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="-200" NAME="cash -200" DATE="2011-07-12 11:55:01" />
	<OPERATION ID="1000000000017" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="300" NAME="cash +300" DATE="2011-07-11 11:55:01" />
	<OPERATION ID="1000000000018" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="100" NAME="cash +100" DATE="2011-07-10 11:55:01" />
	<OPERATION ID="1000000000019" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="-200" NAME="cash -200" DATE="2011-07-09 11:55:01" />
	<OPERATION ID="1000000000020" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="300" NAME="cash +300" DATE="2011-07-08 11:55:01" />
	<OPERATION ID="1000000000021" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="100" NAME="cash +100" DATE="2011-07-07 11:55:01" />
	<OPERATION ID="1000000000022" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="-200" NAME="cash -200" DATE="2011-07-06 11:55:01" />
	<OPERATION ID="1000000000023" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="300" NAME="cash +300" DATE="2011-07-05 11:55:01" />
	<OPERATION ID="1000000000024" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="100" NAME="cash +100" DATE="2011-07-04 11:55:01" />
	<OPERATION ID="1000000000025" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="-200" NAME="cash -200" DATE="2011-07-03 11:55:01" />
	<OPERATION ID="1000000000026" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="300" NAME="cash +300" DATE="2011-07-02 11:55:01" />
	<OPERATION ID="1000000000027" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="MISC" AMOUNT="100" NAME="cash +100" DATE="2011-07-01 11:55:01" />

	<OPERATION ID="100000000050" ACCOUNT="1000000000" STATUS="RESOLVED" TYPE="TRANSFER" AMOUNT="100" NAME="transfer +100" DATE="2011-07-01 11:55:01" />
	<OPERATION ID="100000000051" ACCOUNT="1000000000" STATUS="PENDING" TYPE="TRANSFER" AMOUNT="100" NAME="transfer +100" DATE="2011-07-01 11:56:01" />

	<OPERATION ID="100000000100" ACCOUNT="1000000001" STATUS="RESOLVED" TYPE="MISC" AMOUNT="400" NAME="cash +400" DATE="2011-07-25 11:55:01" />
	<OPERATION ID="100000000101" ACCOUNT="1000000001" STATUS="RESOLVED" TYPE="MISC" AMOUNT="500" NAME="cash +500" DATE="2011-07-24 11:55:01" />
	<OPERATION ID="100000000102" ACCOUNT="1000000001" STATUS="RESOLVED" TYPE="MISC" AMOUNT="-600" NAME="cash -600" DATE="2011-07-23 11:55:01" />
	<OPERATION ID="100000000103" ACCOUNT="1000000001" STATUS="RESOLVED" TYPE="MISC" AMOUNT="700" NAME="cash +700" DATE="2011-07-22 11:55:01" />

</dataset>
