=== anote2011/excilys-bank/excilys-bank-web/src/main/resources/data/dataSet-data.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dataset ANY>
<!ELEMENT USER EMPTY>
<!ATTLIST USER
		ID CDATA #REQUIRED
		FIRSTNAME CDATA #REQUIRED
		LASTNAME CDATA #REQUIRED
		LOGIN CDATA #REQUIRED
		PASSWORD CDATA #REQUIRED
		EMAIL CDATA #REQUIRED
>
<!ELEMENT USER_ROLE EMPTY>
<!ATTLIST USER_ROLE
		USER_ID CDATA #REQUIRED
		ROLE_ID CDATA #REQUIRED
>

<!ELEMENT ACCOUNT EMPTY>
<!ATTLIST ACCOUNT
		ID CDATA #REQUIRED
		NUMBER CDATA #REQUIRED
		TYPE CDATA #REQUIRED
		BALANCE CDATA #REQUIRED
		BALANCE_DATE CDATA #REQUIRED
>
<!ELEMENT USER_ACCOUNT EMPTY>
<!ATTLIST USER_ACCOUNT
		USER_ID CDATA #REQUIRED
		ACCOUNT_ID CDATA #REQUIRED
>
<!ELEMENT CARD EMPTY>
<!ATTLIST CARD
		ID CDATA #REQUIRED
		NUMBER CDATA #REQUIRED
		TYPE CDATA #REQUIRED
		ACCOUNT CDATA #REQUIRED
		PENDING CDATA ""
		PENDING_DATE CDATA ""
>
<!ELEMENT OPERATION EMPTY>
<!ATTLIST OPERATION
		ID CDATA #REQUIRED
		ACCOUNT CDATA #REQUIRED
		STATUS CDATA #REQUIRED
		ACCOUNT CDATA #REQUIRED
		TYPE CDATA #REQUIRED
		CARD CDATA ""
		AMOUNT CDATA #REQUIRED
		NAME CDATA #REQUIRED
		DATE CDATA #REQUIRED
>

=== anote2011/excilys-bank/excilys-bank-web/src/main/resources/data/dataSet-data-old.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "dataSet-data.dtd">
<dataset>

	<USER ID="0" FIRSTNAME="Stephane" LASTNAME="Landelle" LOGIN="slandelle" PASSWORD="password" EMAIL="slandelle@excilys.com" />
	<USER ID="1" FIRSTNAME="Romain" LASTNAME="Sertelon" LOGIN="rsertelon" PASSWORD="password" EMAIL="rsertelon@excilys.com" />

	<USER_ROLE USER_ID="0" ROLE_ID="ROLE_USER" />
	<!-- <USER_ROLE USER_ID="0" ROLE_ID="ROLE_ADMIN" /> -->
	<USER_ROLE USER_ID="1" ROLE_ID="ROLE_USER" />

	<ACCOUNT ID="0" NUMBER="0123456789AAXX" TYPE="PERSONNAL_CHECKING" BALANCE="50.00" BALANCE_DATE="2011-08-02 11:55:01" />
	<ACCOUNT ID="1" NUMBER="0123456789AAYY" TYPE="JOINT_CHECKING" BALANCE="500.00" BALANCE_DATE="2011-08-02 11:55:01" />
	<ACCOUNT ID="2" NUMBER="0123456789AAZZ" TYPE="PEL" BALANCE="1000.00" BALANCE_DATE="2011-08-02 11:55:01" />

	<USER_ACCOUNT USER_ID="0" ACCOUNT_ID="0" />
	<USER_ACCOUNT USER_ID="0" ACCOUNT_ID="1" />
	<USER_ACCOUNT USER_ID="0" ACCOUNT_ID="2" />

	<CARD ID="0" NUMBER="XXXXX1" TYPE="CREDIT" ACCOUNT="0" PENDING="-200" PENDING_DATE="2011-08-02 11:55:01" />
	<CARD ID="1" NUMBER="XXXXX2" TYPE="DEBIT" ACCOUNT="0" />
	<CARD ID="2" NUMBER="XXXXX3" TYPE="DEBIT" ACCOUNT="1" />

	<OPERATION ID="28" ACCOUNT="0" STATUS="RESOLVED" TYPE="CARD" CARD="0" AMOUNT="-100" NAME="cash -100" DATE="2011-07-01 11:55:01" />
	<OPERATION ID="29" ACCOUNT="0" STATUS="PENDING" TYPE="CARD" CARD="0" AMOUNT="-200" NAME="cash -200" DATE="2011-08-01 11:55:01" />

	<OPERATION ID="0" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="100" NAME="cash +100" DATE="2011-07-28 11:55:01" />
	<OPERATION ID="1" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="-200" NAME="cash -200" DATE="2011-07-27 11:55:01" />
	<OPERATION ID="2" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="300" NAME="cash +300" DATE="2011-07-26 11:55:01" />
	<OPERATION ID="3" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="100" NAME="cash +100" DATE="2011-07-25 11:55:01" />
	<OPERATION ID="4" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="-200" NAME="cash -200" DATE="2011-07-24 11:55:01" />
	<OPERATION ID="5" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="300" NAME="cash +300" DATE="2011-07-23 11:55:01" />
	<OPERATION ID="6" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="100" NAME="cash +100" DATE="2011-07-22 11:55:01" />
	<OPERATION ID="7" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="-200" NAME="cash -200" DATE="2011-07-21 11:55:01" />
	<OPERATION ID="8" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="300" NAME="cash +300" DATE="2011-07-20 11:55:01" />
	<OPERATION ID="9" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="100" NAME="cash +100" DATE="2011-07-19 11:55:01" />
	<OPERATION ID="10" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="-200" NAME="cash -200" DATE="2011-07-18 11:55:01" />
	<OPERATION ID="11" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="300" NAME="cash +300" DATE="2011-07-17 11:55:01" />
	<OPERATION ID="12" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="100" NAME="cash +100" DATE="2011-07-16 11:55:01" />
	<OPERATION ID="13" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="-200" NAME="cash -200" DATE="2011-07-15 11:55:01" />
	<OPERATION ID="14" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="300" NAME="cash +300" DATE="2011-07-14 11:55:01" />
	<OPERATION ID="15" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="100" NAME="cash +100" DATE="2011-07-13 11:55:01" />
	<OPERATION ID="16" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="-200" NAME="cash -200" DATE="2011-07-12 11:55:01" />
	<OPERATION ID="17" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="300" NAME="cash +300" DATE="2011-07-11 11:55:01" />
	<OPERATION ID="18" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="100" NAME="cash +100" DATE="2011-07-10 11:55:01" />
	<OPERATION ID="19" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="-200" NAME="cash -200" DATE="2011-07-09 11:55:01" />
	<OPERATION ID="20" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="300" NAME="cash +300" DATE="2011-07-08 11:55:01" />
	<OPERATION ID="21" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="100" NAME="cash +100" DATE="2011-07-07 11:55:01" />
	<OPERATION ID="22" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="-200" NAME="cash -200" DATE="2011-07-06 11:55:01" />
	<OPERATION ID="23" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="300" NAME="cash +300" DATE="2011-07-05 11:55:01" />
	<OPERATION ID="24" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="100" NAME="cash +100" DATE="2011-07-04 11:55:01" />
	<OPERATION ID="25" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="-200" NAME="cash -200" DATE="2011-07-03 11:55:01" />
	<OPERATION ID="26" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="300" NAME="cash +300" DATE="2011-07-02 11:55:01" />
	<OPERATION ID="27" ACCOUNT="0" STATUS="RESOLVED" TYPE="MISC" AMOUNT="100" NAME="cash +100" DATE="2011-07-01 11:55:01" />

	<OPERATION ID="50" ACCOUNT="0" STATUS="RESOLVED" TYPE="TRANSFER" AMOUNT="100" NAME="transfer +100" DATE="2011-07-01 11:55:01" />
	<OPERATION ID="51" ACCOUNT="0" STATUS="PENDING" TYPE="TRANSFER" AMOUNT="100" NAME="transfer +100" DATE="2011-07-01 11:56:01" />

	<OPERATION ID="100" ACCOUNT="1" STATUS="RESOLVED" TYPE="MISC" AMOUNT="400" NAME="cash +400" DATE="2011-07-25 11:55:01" />
	<OPERATION ID="101" ACCOUNT="1" STATUS="RESOLVED" TYPE="MISC" AMOUNT="500" NAME="cash +500" DATE="2011-07-24 11:55:01" />
	<OPERATION ID="102" ACCOUNT="1" STATUS="RESOLVED" TYPE="MISC" AMOUNT="-600" NAME="cash -600" DATE="2011-07-23 11:55:01" />
	<OPERATION ID="103" ACCOUNT="1" STATUS="RESOLVED" TYPE="MISC" AMOUNT="700" NAME="cash +700" DATE="2011-07-22 11:55:01" />

</dataset>
